# Generated by Django 5.2.6 on 2025-09-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0004_alter_item_acquired_dt_alter_item_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='user',
            new_name='character',
        ),
        migrations.AlterField(
            model_name='character',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_inventory.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='by_day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='by_week',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='websource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websource',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
