# Generated by Django 5.2.6 on 2025-10-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0005_alter_group_category_remove_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='character',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='note',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Item',
        ),
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.CreateModel(
            name='DateReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_dt', models.DateTimeField()),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('acknowledged_dt', models.DateTimeField(null=True)),
                ('reoccuring', models.BooleanField()),
                ('reoccuring_timespan', models.DurationField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_inventory.note')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('acknowledged_dt', models.DateTimeField(null=True)),
                ('time', models.TimeField()),
                ('on_monday', models.BooleanField()),
                ('on_tuesday', models.BooleanField()),
                ('on_wednesday', models.BooleanField()),
                ('on_thursday', models.BooleanField()),
                ('on_friday', models.BooleanField()),
                ('on_saturday', models.BooleanField()),
                ('on_sunday', models.BooleanField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_inventory.note')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=8,on_delete=django.db.models.deletion.CASCADE, related_name='image', to='my_inventory.item'),
            preserve_default=False,
        ),
    ]
