# Generated by Django 5.2.6 on 2025-10-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0006_remove_stats_character_remove_reminder_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='websource',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_friday',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_monday',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_saturday',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_sunday',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_thursday',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_tuesday',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='weeklyreminder',
            old_name='on_wednesday',
            new_name='wednesday',
        ),
    ]
