# Generated by Django 5.2.6 on 2025-10-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0008_alter_image_name_alter_note_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datereminder',
            old_name='reoccuring_timespan',
            new_name='reoccuring_interval',
        ),
    ]
