# Generated by Django 5.2.6 on 2025-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0009_rename_reoccuring_timespan_datereminder_reoccuring_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereminder',
            name='reoccuring_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
