# Generated by Django 5.2.6 on 2025-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0010_alter_datereminder_reoccuring_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereminder',
            name='acknowledged_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreminder',
            name='acknowledged_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
