# Generated by Django 5.2.6 on 2025-10-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0011_alter_datereminder_acknowledged_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datereminder',
            old_name='reoccuring',
            new_name='reoccurring',
        ),
        migrations.RenameField(
            model_name='datereminder',
            old_name='reoccuring_interval',
            new_name='reoccurring_interval',
        ),
    ]
