# Generated by Django 5.2.6 on 2025-10-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0012_rename_reoccuring_datereminder_reoccurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereminder',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_reminder', to='my_inventory.note'),
        ),
        migrations.AlterField(
            model_name='weeklyreminder',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reminder', to='my_inventory.note'),
        ),
    ]
