# Generated by Django 5.2.6 on 2025-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_inventory', '0013_alter_datereminder_note_alter_weeklyreminder_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datereminder',
            name='reoccurring',
        ),
        migrations.RemoveField(
            model_name='datereminder',
            name='reoccurring_interval',
        ),
    ]
